### ISSUE TITLE
"Error reading backup properties" when creating backup for the first time

### ISSUE THREAD

**Issue by janopae** [redromnon/iBackep#10]
**Describe the bug**

When I use iBackep for the first time, it failed with the error pasted below. It is the same error message that happens when using pymobiledevice for the first time without the `--full` option.

The output also contains `New backup folder?: False`, which suggests that the detection of an empty backup destination doesn't work.

After using pymobiledevice with the `--full` option on the command line to create the first backup, creating incremental backups using iBackep works without problems.

**To Reproduce**

1. Select an empty target directory
2. Click on 'Create backup'

It says it failed to create a backup.

This is the output:

```
iPhone 6s
New backup folder?: False
Backup running...
0.0
0.0
Traceback (most recent call last):
  File "ui/operations.py", line 58, in backup
  File "pymobiledevice3/services/mobilebackup2.py", line 91, in backup
  File "pymobiledevice3/services/device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}

iPhone 6s
New backup folder?: False
Backup running...
0.0
0.0
Traceback (most recent call last):
  File "ui/operations.py", line 58, in backup
  File "pymobiledevice3/services/mobilebackup2.py", line 91, in backup
  File "pymobiledevice3/services/device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}

```

The error message looks similar to when you use `pymobiledevice3` for the first time without the `--full` option.

**Expected behavior**
Backup being created

**System (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
 - Version: 2.0.2

**Comment by redromnon** [comment]
Please check the latest release if this issue is solved - https://github.com/redromnon/iBackep/releases/tag/v2.0.3
