### ISSUE TITLE
Executing backup

### ISSUE THREAD

**Issue by kaaduu** [redromnon/iBackep#8]
version 2.0.0 used

after proividing pin code this error is generated nothing happnes onlu backup failed messsage in gui

Backup running...
0.0
0.0
Traceback (most recent call last):
  File "ui/operations.py", line 58, in backup
  File "pymobiledevice3/services/mobilebackup2.py", line 91, in backup
  File "pymobiledevice3/services/device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}

**Comment by redromnon** [comment]
Pin-code? In this sense did you enter a password? Right now, creating encrypted backups is not supported. Only unencrypted backups can be made.

**Comment by redromnon** [comment]
Also, have you provided the path to a previous backup or creating a new backup for the first time?

**Comment by trenchcoatjedi** [comment]
Version 2.0.2

Downloaded binary and change permissions with chmod u+x ibackep

If Run without super user privileges, get this error:

(flet:6953): dbind-WARNING **: 08:28:24.839: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0: Permission denied

Run as super user and backup fails each time. This is an unencrypted backup attempt.

$ sudo ./ibackep 

(flet:7147): Gdk-CRITICAL **: 08:28:50.352: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
iPhone SE (2nd gen)
New backup folder?: False
Backup running...
0.0
0.0
Traceback (most recent call last):
  File "ui/operations.py", line 58, in backup
  File "pymobiledevice3/services/mobilebackup2.py", line 91, in backup
  File "pymobiledevice3/services/device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}

**Comment by redromnon** [comment]
Try backing up to a new folder and check if it works.

**Comment by trenchcoatjedi** [comment]
I tried multiple folders with no luck. I was able to backup using idevicebackup2 cmd line however.

**Comment by redromnon** [comment]
Were you getting the same error for new empty folders too?

**Comment by trenchcoatjedi** [comment]
Yes, same error no matter what folder I chose.

**Comment by redromnon** [comment]
Does it display `New backup folder?: True` for a new folder? 


```
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}
```
The above error occurs if the app assumes a completely new folder as an existing backup.

**Comment by gustavobsch** [comment]
Same issue here, ubuntu 24

```

$ ./ibackep 

(flet:70909): Gdk-CRITICAL **: 10:34:08.036: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
iPhone SE (3rd gen)
New backup folder?: False
Backup running...
0.0
0.0
Traceback (most recent call last):
  File "ui/operations.py", line 58, in backup
  File "pymobiledevice3/services/mobilebackup2.py", line 91, in backup
  File "pymobiledevice3/services/device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Error reading backup properties (MBErrorDomain/205). Underlying error: Error deserializing properties: Cannot parse a NULL or zero-length data (MBErrorDomain/11).', 'MessageName': 'Response'}


```

**Comment by Eisenbahnfan2015** [comment]
I also have the same error and chose to encrypt the backups in iTunes at an earlier time. It's probably because of this encryption that seems to be stored inside the device that it's not working.

**Comment by redromnon** [comment]
Please check the latest release if this issue is solved - https://github.com/redromnon/iBackep/releases/tag/v2.0.3
